os:
  - linux
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "0.10.29"
  - "0.12.0"
  - "4.0.0"
notifications:
  recipients:
    - i@yanyiwu.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
  - osx
script: 
  - npm test
